all:	Manderbrot.h manderbrot.cpp bitmap.cpp bitmap.h
	g++ -std=c++11 -o test manderbrot.cpp bitmap.cpp

debug:	Manderbrot.h manderbrot.cpp bitmap.cpp bitmap.h
	g++ -std=c++11 -o test manderbrot.cpp bitmap.cpp -g

clean:
	rm -f test